name: Deploy Project
on: [push, worflow_dispatch] # multiplos triggers
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3 # apenas para demonstrar, pois nodejs já vem instalado na imagem usada de ubuntu-latest
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: test #por padrao, rodam em paralelo. Se quiser sequencial, usar needs
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3 # apenas para demonstrar, pois nodejs já vem instalado na imagem usada de ubuntu-latest
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
